# Generated by Django 2.1.5 on 2020-04-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle', '0002_auto_20200428_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Assigned', 'Assigned')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='works',
            field=models.CharField(choices=[('Dish washes', 'Dish washes'), ('House Cleaning', 'House Cleaning'), ('WaterCAn', 'WaterCAn'), ('Washroom Cleaning', 'Washroom Cleaning')], max_length=200, null=True),
        ),
    ]
