# Generated by Django 2.1.5 on 2020-04-28 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle', '0004_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='category',
            field=models.CharField(choices=[('ROOM RENT', 'Room Rent'), ('Maintance', 'Maintance')], max_length=200, null=True),
        ),
    ]
