# Generated by Django 2.1.5 on 2020-04-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle', '0006_auto_20200429_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tags',
            field=models.ManyToManyField(to='cycle.Tag'),
        ),
    ]
