# Generated by Django 2.1.5 on 2020-05-02 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cycle', '0008_order_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='order',
            name='category',
        ),
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
    ]
