# Generated by Django 2.1.5 on 2020-05-02 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cycle', '0009_auto_20200502_1107'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
