# Generated by Django 2.1.5 on 2020-05-16 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cycle', '0013_auto_20200513_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
