# Generated by Django 2.1.5 on 2020-05-21 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cycle', '0018_product_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='phone',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cycle.Customer'),
        ),
    ]
