# Generated by Django 2.1.5 on 2020-05-21 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle', '0019_auto_20200521_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='product',
            name='customer',
        ),
        migrations.AddField(
            model_name='product',
            name='customer',
            field=models.ManyToManyField(to='cycle.Customer'),
        ),
    ]
