# Generated by Django 2.1.5 on 2020-05-22 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cycle', '0021_auto_20200521_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bills', models.CharField(choices=[('RicePacket', 'Ricepacket'), ('Watercans', 'Watercans'), ('Curries', 'Curries'), ('WifiBill', 'WifiBill'), ('Rommproducts', 'Roomproducts')], max_length=120, null=True)),
                ('price', models.IntegerField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cycle.Customer')),
            ],
        ),
    ]
