# Generated by Django 2.1.5 on 2020-06-20 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cycle', '0023_auto_20200527_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='district',
        ),
        migrations.DeleteModel(
            name='College',
        ),
        migrations.DeleteModel(
            name='District',
        ),
    ]
